### ISSUE TITLE
ENH: Support simplified test configuration (with docker setup typically via application-test.yml)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1283]
Provide a plugin `io.ebean.test` : `ebean-test-config` that can be added as a test dependency. This can then:
- Simplify testing configuration
- Manage docker containers to suit the active testing configuration

Note that this is actually a refactoring of the `ebean-docker-run` project which we have been using for some time and we will rename that project as part of this. 

#### Basic H2  
```yml
ebean:
  test:
    platform: h2
```
This is all we need to run tests against H2 using defaults.

#### Basic Postgres   
```yml
ebean:
  test:
    platform: postgres
    dbName: test_myapp
```
Run tests against Postgres using defaults.
- Creates and runs Postgres docker container (default version 9.6 currently)
- Executes docker commands to create database, database user, extensions (default hstore and pgcrypto)
- Runs DDL in mode `dropCreate` (ebean.ddl.generate=true, ebean.ddl.run=true)

#### Run selected platform
We can run against a platform using the `db` system property

```sh
mvn clean test -Ddb=sqlserver
```

#### Multiple platform with overrides from defaults
```yml
ebean:
  test:
    platforms: postgres, mysql, sqlserver
    dbName: test_myapp
    ddlMode: dropCreate  # none | dropCreate | create | migrations
    postgres:
      version: 9.7
      extensions: hstore,pgcrypto
    mysql:
      version: 5.7
    sqlserver:
       version: 2017-CU2
```
