### ISSUE TITLE
Refactor and rename DbTypeConfig to Platform config to support multi-platform db migration 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1342]
This is the functionality of Rolands PR #1324 

Support Multi-platform DB migration generation with the ability to control `dbuuid` and `idType` for each platform being generated.

### Example

```java

    DbMigration dbMigration = DbMigration.create();
    dbMigration.addPlatform(Platform.POSTGRES, "postgres");
    dbMigration.addPlatform(Platform.SQLSERVER17, "sqlserver17");
    dbMigration.addPlatform(Platform.ORACLE, "oracle");
    dbMigration.addPlatform(Platform.MYSQL, "mysql");

    dbMigration.generateMigration();

```
With the ability to configure `dbuuid` and `idType` for each platform being generated.
```yml
dbmigration:
  platform:
    sqlserver17:
      dbuuid: VARCHAR
    oracle:
      idType: IDENTITY
    mysql:
      dbuuid: BINARY_OPTIMIZED
```

## Details

Rename DbTypeConfig to PlatformConfig
Move ServerConfig.DbUuid to PlatformConfig.DbUuid

Moved  idType, databaseSequenceBatchSize, databaseBooleanTrue, databaseBooleanFalse, and allQuotedIdentifiers from ServerConfig to PlatformConfig,

Note that the ServerConfig API hasn't changed but the get/set methods now proxy through to  PlatformConfig.
