### ISSUE TITLE
Update the #1283 ENH: Support simplified test configuration (with docker setup typically via application-test.yml)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1343]
Split the configuration into pre and post properties load apply. This will break the current ebean-test-config (2.1.1) but it is a good change to ma

This will enable the split of 'docker setup' and 'auto configure' in ebean-test-config.

Refer to #1283

#### Basic H2  
```yml
ebean:
  test:
    platform: h2
```
This is all we need to run tests against H2 using defaults.

#### Basic Postgres   
```yml
ebean:
  test:
    platform: postgres
    dbName: test_myapp
```
