### ISSUE TITLE
Add support to set ebean.dbSchema ... (~ default DB schema) with create-all.sql and DB migrations (so it all just works)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1442]
## Usage Scenario 

Where we want to use a db schema (typically Postgres) and we want all the things below to just work.
- DB Migration  (create the schema if required)
- Testing with create-all.sql DDL 
- Testing with Docker via `ebean-test-config` 
We want this all to just work and we want there to be consistency in terms of DB schema and DDL between migrations and create-all (we want the tables to be in the schema in both cases).

## How to use (Postgres)

Specify `ebean.dbSchema` via properties, yml or ServerConfig.
```yml
ebean:
  dbSchema: myapp
```

## Expected behaviour

- DB Migration Runner will have the schema set and will create the schema if required prior to running any migrations

- Running DDL (`create-all.sql` etc) will create the schema if required.  This means that we have consistency between running migrations and running create-all ddl.

#### Postgres note when using ebean-test-config

If the db schema matches the db username then `ebean-test-config` will not modify the jdbc url as we expect to use the expected Postgres behaviour where the search path is `$user,public`.  That is, the tables are created into the db schema in this case without setting `currentSchema`.

e.g. schema = myapp, dbUser=myapp ... so these match (no need to use currentSchema).
```
postgres.dbName=mydb
postgres.dbUser=myapp
postgres.url=jdbc:postgresql://localhost:6432/mydb
```

If the db schema does not match the db username then `ebean-test-config` will modify the jdbc url appending `?currentSchema=myapp` to set the current schema to use.

e.g. schema = myapp, dbUser=myuser ... so these do not match (need to use currentSchema).
```
postgres.dbName=mydb
postgres.dbUser=myuser
postgres.url=jdbc:postgresql://localhost:6432/mydb?currentSchema=myapp
```

The expectation is that when using Postgres we want the dbUser and dbSchema to match and not have to do anything regarding `currentSchema` or `search path`.

#### ebean-test-config

Note that `ebean-test-config` has been updated to default the dbUser to the same as the schema if a schema has been specified.  If no schema has been specified then the dbUser will default to be the same as the dbName as per existing behaviour.

# Summary

We should be able to just set `ebean.dbSchema=myapp` ... and for everything to just work (as long as we use ebean-test-config).

Postgres users will most likely have the dbUser and dbSchema match.  When they do this we don't need to use currentSchema or adjust the search path.  If they don't match the likely issues people might see would be that the search path is setup without including the `public` schema and that there are some things (e.g. hstore extension in the public schema) that now the connection does not see / not in the search path. 

------
## The actual code changes here

- Pass the schema to DBMigration Runner (so that it is used there)
- Modify the DDL execution for testing (DdlGenerator) such that it creates the schema if required
- Modify the DdlGenerator to use a single java.sql.Connection to run all the DDL (init, drop, create, seed).  This is not strictly related to this schema handling change. 
 
----
## Postgres Example use (with ebean-test-config 11.18.2+)

application.yml
```yml
ebean:
  dbSchema: myapp
```

application-test.yml
```yml
ebean:
  test:
#    shutdownHook: stop
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: mydb
#    dbUser: myapp
#    dbPassword: test

    postgres:
      containerName: ut_pg10
      version: 10
#      extensions: hstore,pgcrypto
#      url: jdbc:postgresql://localhost:6432/mydb
```
