### ISSUE TITLE
ENH: Add support for mariadb docker test container

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1771]
Refer to https://github.com/ebean-orm/ebean-test-config/issues/29

Effectively we can specify `mariadb` as the platform in `application-test.yaml` like:

```yml
ebean:
  test:
    platform: mariadb # h2, postgres, mysql, mariadb, oracle, sqlserver, hana, sqlite
    ddlMode: dropCreate 
    dbName: my_app
```
