### ISSUE TITLE
[ebean-test] Allow docker configuration options to be at ebean.test.X as well as ebean.test.<platform>.X

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2686]
## Expected behavior

Properties set at `ebean.test.X` should intuitively work like `ebean.test.image: postgis/postgis`

```yml
ebean:
  test:
    image: postgis/postgis
```

## Actual behavior

Many properties like `image` need to be specified under the platform like `ebean.test.foo.image: postgis/postgis`

```yml
ebean:
  test:
    platform: foo
    foo: 
      image: postgis/postgis
```

This change makes setting those properties work at the higher level if that is what people do.
